"""Presentation layer: derived state + prices + returns + risk → a report.

Pure functions only — no I/O, no logging side-effects.

Slice 4 split this into two stages so the same content can leave as plain text
(stdout), markdown (a file in ``reports/``), or HTML (an email body) without
threading an ``output_format`` flag through every section:

    build_report_data(...)  -> ReportData      # ordered sections as data
    render_text / _markdown / _html(ReportData) -> str

``ReportData`` is the single seam. Sections decide *what* to show and in *what
order* (drawdown leads — what the user feels); renderers decide *how*. Each
section body is a tuple of pre-formatted text lines: the careful column
alignment of the holdings grid is content, so it lives once and the markdown /
HTML renderers preserve it in monospace blocks. A future richer HTML renderer
(real ``<table>``) can consume the same ``ReportData`` without changing callers.
"""

from __future__ import annotations

import html
import math
from collections import Counter
from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone

from app.backtest import BacktestResult
from app.derive import DerivedState
from app.metadata import MetadataResult
from app.prices import PriceRow
from app.returns import ReturnsSummary
from app.risk import NOISY_THRESHOLD_DAYS, DollarDrawdown, DrawdownInfo, MetricCI, RiskSummary
from app.screen import CandidateScreen
from app.strategy import Suggestion

_NA = "n/a"
_DISCLAIMER = (
    "Generated by asset-management. Figures are deterministic and reconciled "
    "against ghostfolio + quantstats; this is not financial advice."
)


# ── structured intermediate representation ─────────────────────────────────


@dataclass(frozen=True)
class Section:
    """One report section. ``title`` empty → rendered without a heading."""

    title: str
    lines: tuple[str, ...]


@dataclass(frozen=True)
class ReportData:
    """The whole report as ordered sections plus delivery metadata."""

    title: str
    asof_date: str
    sections: tuple[Section, ...]
    generated_at: datetime


# ── value formatting (shared by every section) ─────────────────────────────


def _pct_or_na(x: float | None) -> str:
    return _NA if x is None or not math.isfinite(x) else f"{x * 100:+.2f}%"


def _usd(x: float) -> str:
    """Dollar amount with sign, no cents: `$1,234` or `-$1,234`."""
    return f"-${abs(x):,.0f}" if x < 0 else f"${x:,.0f}"


def _ci(ci: MetricCI, *, scale: float, suffix: str) -> str:
    """Render a MetricCI; values multiplied by `scale` with `suffix` appended.

    Falls back to `n/a` when the point estimate is non-finite (e.g. Calmar with
    no drawdown → nan, Sortino with no downside → inf)."""
    if not math.isfinite(ci.point):
        return _NA
    s = suffix
    return (
        f"{ci.point * scale:+.2f}{s}  "
        f"(95% CI {ci.low * scale:+.2f}{s} .. {ci.high * scale:+.2f}{s})"
    )


def _ci_pct(ci: MetricCI) -> str:
    """MetricCI whose values are fractions, rendered as percentages with a band."""
    return _ci(ci, scale=100.0, suffix="%")


def _ci_ratio(ci: MetricCI) -> str:
    """MetricCI whose values are unitless ratios (Sharpe etc.)."""
    return _ci(ci, scale=1.0, suffix="")


def _mag_ci(ci: MetricCI) -> str:
    """Positive-magnitude percentage CI (Ulcer/CDaR) — no leading sign."""
    if not math.isfinite(ci.point):
        return _NA
    return (
        f"{ci.point * 100:.2f}%  "
        f"(95% CI {ci.low * 100:.2f}% .. {ci.high * 100:.2f}%)"
    )


# ── build: state/prices/returns/risk → ordered sections ────────────────────


def build_report_data(
    state: DerivedState,
    prices: dict[str, PriceRow] | None = None,
    returns: ReturnsSummary | None = None,
    risk: RiskSummary | None = None,
    *,
    suggestions: list[Suggestion] | None = None,
    backtest: BacktestResult | None = None,
    missing_tickers: list[str] | None = None,
    asof: date | None = None,
    generated_at: datetime | None = None,
    twr_excluded: list[str] | None = None,
    dollar_dd: DollarDrawdown | None = None,
    metadata: MetadataResult | None = None,
    candidates: list[CandidateScreen] | None = None,
) -> ReportData:
    """Assemble the deterministic brief as ordered sections.

    When present, SUGGESTED ACTIONS leads (it's the call-to-action the user opens
    the brief for); the drawdown-first risk/return context follows.

    `asof` dates the report (its title and the ``reports/<asof>.md`` filename).
    `generated_at` is the run's wall-clock instant, used for the provenance
    footer's price-age and "as of HH:MM" stamp. BOTH are passed by the
    composition root so this function is **pure** (same inputs → same output) —
    no hidden clock read. The lone `datetime.now()` fallback below is for callers
    that don't supply one (tests); cli always passes the real value.
    """
    prices = prices or {}
    missing_tickers = missing_tickers or []
    twr_excluded = twr_excluded or []
    gen = generated_at if generated_at is not None else datetime.now(timezone.utc)
    if asof is None:
        # Derived from the inputs, not a fresh clock read (the function stays pure):
        # the returns window's end, else the run instant's date. Resolved up front so
        # every consumer (the SECURITIES ages, the title) uses the SAME date.
        asof = returns.asof_date if returns is not None else gen.date()
    sections: list[Section] = []

    if suggestions:
        sections.append(_section_suggestions(suggestions))
    if risk is not None:
        sections.append(_section_drawdown(risk, dollar_dd))
        sections.append(_section_risk_adjusted(risk))
    if returns is not None and returns.period_days > 0:
        sections.append(_section_returns(returns, twr_excluded))
    if state.positions or prices:  # skip the empty holdings table on a no-book (backtest-only) run
        sections.append(_section_holdings(state, prices))
    if metadata is not None and (metadata.rows or metadata.missing):
        sections.append(_section_securities(metadata, asof))
    if candidates:
        sections.append(_section_candidates(candidates))
    if backtest is not None and backtest.legs:
        sections.append(_section_backtest(backtest))

    footer = _footer_section(prices, missing_tickers, gen)
    if footer is not None:
        sections.append(footer)

    asof_str = asof.isoformat()
    return ReportData(
        title=f"Portfolio brief — {asof_str}",
        asof_date=asof_str,
        sections=tuple(sections),
        generated_at=gen,
    )


_REBALANCE_LABEL = {
    "to_total": "rebalance to target",
    "cash_flow_only": "deploy new cash (no sells)",
    "fixed_dca": "fixed DCA into target mix",
    "bands": "threshold-band rebalance",
}


def _section_suggestions(suggestions: list[Suggestion]) -> Section:
    """The actionable panel: per-ticker buy/sell/hold, each paired to its rule."""
    rule = suggestions[0].rule if suggestions else ""
    label = _REBALANCE_LABEL.get(rule, rule)
    lines = [
        f"{'ticker':7}{'cur%':>7}{'tgt%':>7}{'action':>7}"
        f"{'$':>13}{'shares':>12}   why",
        "-" * 78,
    ]
    # Biggest trades first; holds (0) sink to the bottom.
    ordered = sorted(suggestions, key=lambda s: (-s.dollars, s.ticker))
    buy_total = sell_total = 0.0
    for s in ordered:
        sign = 1.0 if s.action == "buy" else -1.0 if s.action == "sell" else 0.0
        if s.action == "buy":
            buy_total += s.dollars
        elif s.action == "sell":
            sell_total += s.dollars
        dollars = f"{sign * s.dollars:+13.2f}" if s.action != "hold" else f"{'-':>13}"
        shares = f"{sign * s.shares:+12.3f}" if s.action != "hold" else f"{'-':>12}"
        lines.append(
            f"{s.ticker:7}{s.current_weight * 100:7.1f}{s.target_weight * 100:7.1f}"
            f"{s.action.upper():>7}{dollars}{shares}   {s.reason}"
        )
    net = buy_total - sell_total
    lines.append(
        f"Buy ${buy_total:,.2f} · Sell ${sell_total:,.2f} · "
        f"net {'+' if net >= 0 else '-'}${abs(net):,.2f} "
        f"({'cash to deploy' if net > 0 else 'cash freed' if net < 0 else 'cash-neutral'})"
    )
    lines.append("Suggestions are discipline, not predictions; act or override.")
    return Section(f"SUGGESTED ACTIONS ({label})", tuple(lines))


def _section_drawdown(
    risk: RiskSummary, dollar_dd: DollarDrawdown | None = None
) -> Section:
    dd: DrawdownInfo = risk.drawdown
    rec = dd.recovery_date.isoformat() if dd.recovery_date else "not yet recovered"
    lines = [
        f"Max drawdown:      {_ci_pct(risk.max_drawdown_ci)}",
        f"  peak {dd.peak_date} → trough {dd.trough_date} → {rec}  "
        f"({dd.duration_days} days)",
        f"Ulcer index:       {_mag_ci(risk.ulcer_index)}",
        f"CDaR (worst 5%):   {_mag_ci(risk.cdar)}",
        f"You've spent {dd.time_underwater_pct * 100:.0f}% of this period "
        "below a previous high.",
    ]
    if dollar_dd is not None:
        d_rec = (
            dollar_dd.recovery_date.isoformat()
            if dollar_dd.recovery_date else "not yet recovered"
        )
        lines.append(
            f"Gains given back: {_usd(dollar_dd.giveback_dollars)}  — peak profit "
            f"{_usd(dollar_dd.peak_pnl)} ({dollar_dd.peak_date}) → "
            f"{_usd(dollar_dd.trough_pnl)} ({dollar_dd.trough_date}) → {d_rec}"
        )
        lines.append(
            "  (dollars of profit given back from a peak; flow-neutral — funding & "
            "transfers don't distort it)"
        )
    lines.extend(_noisy_note(risk))
    return Section("DRAWDOWN (investment, time-weighted)", tuple(lines))


def _noisy_note(risk: RiskSummary) -> list[str]:
    """The shared 'treat as noisy' warning, shown on every metric block."""
    if not risk.is_noisy:
        return []
    return [
        f"  ⚠ based on {risk.n_days} return-days (< {NOISY_THRESHOLD_DAYS} ≈ 2y); "
        "treat these figures as noisy."
    ]


def _section_risk_adjusted(risk: RiskSummary) -> Section:
    lines = [
        f"Sharpe:   {_ci_ratio(risk.sharpe)}",
        f"Sortino:  {_ci_ratio(risk.sortino)}",
        f"Calmar:   {_ci_ratio(risk.calmar)}",
        *_noisy_note(risk),
    ]
    return Section(
        "RISK-ADJUSTED (annualized, 252-day basis, risk-free 0%, ± bootstrap CI)",
        tuple(lines),
    )


def _section_returns(
    returns: ReturnsSummary, twr_excluded: list[str] | None = None
) -> Section:
    twr = returns.true_twr_annualized
    lines = [
        f"Period: {returns.period_start} → {returns.asof_date} "
        f"({returns.period_days} days, ~{returns.period_days / 365.25:.2f}y)",
        f"Time-weighted (true TWR):                {_pct_or_na(twr)}",
        f"Money-weighted (IRR):                    "
        f"{_pct_or_na(returns.money_weighted_annualized)}",
        f"Modified Dietz (approx TWR):             "
        f"{_pct_or_na(returns.modified_dietz_annualized)}",
        "  (point figures: accounting identities over your cash flows, not sampled "
        "statistics → no band; see RISK-ADJUSTED for bootstrapped CIs)",
    ]
    if twr_excluded:
        lines.append(
            f"  ⚠ excluded from TWR & risk: {', '.join(twr_excluded)} "
            "(unadjusted stock split — raw share counts vs split-adjusted prices; "
            "MWR/Dietz unaffected). Corporate-action handling lands in v1.x."
        )
    if any(
        v is None or not math.isfinite(v)
        for v in (twr, returns.money_weighted_annualized,
                  returns.modified_dietz_annualized)
    ):
        lines.append("  (n/a = period too short to annualize, or no real solution)")
    return Section("RETURNS (annualized, 252-day basis)", tuple(lines))


def _section_holdings(state: DerivedState, prices: dict[str, PriceRow]) -> Section:
    held = state.held()
    lines = [
        f"{'ticker':7}{'shares':>10}{'avg cost':>10}{'price':>9}"
        f"{'mkt value':>13}{'unreal':>12}{'realized':>12}",
        "-" * 73,
    ]

    total_mkt = 0.0
    total_unreal = 0.0
    n_priced = 0
    for tk in sorted(held):
        p = held[tk]
        price = prices.get(tk)
        if price is not None:
            mkt = p.shares * price.close
            unreal = mkt - p.cost_basis
            total_mkt += mkt
            total_unreal += unreal
            n_priced += 1
            price_str, mkt_str, unreal_str = (
                f"{price.close:9.2f}", f"{mkt:13.2f}", f"{unreal:+12.2f}"
            )
        else:
            price_str, mkt_str, unreal_str = f"{_NA:>9}", f"{_NA:>13}", f"{_NA:>12}"
        lines.append(
            f"{tk:7}{p.shares:10.3f}{p.avg_cost:10.2f}{price_str}"
            f"{mkt_str}{unreal_str}{state.realized[tk]:+12.2f}"
        )
    lines.append("-" * 73)

    cost = state.total_cost_basis()
    real = state.total_realized()
    fees = state.total_fees()
    lines.append(f"Total cost basis (held): ${cost:,.2f}")
    if prices and n_priced > 0:
        lines.append(f"Market value (priced):   ${total_mkt:,.2f}")
        lines.append(f"Unrealized P&L:          ${total_unreal:+,.2f}")
    lines.append(f"Realized P&L (sells+div): ${real:+,.2f}")
    lines.append(f"Fees paid (informational): ${fees:,.2f}")
    if prices and n_priced > 0:
        # Fees are already netted into cost_basis (buys) and realized (sells);
        # the bottom line must NOT subtract them again.
        lines.append(f"Net P&L (unrealized + realized): ${total_unreal + real:+,.2f}")
    return Section("HOLDINGS", tuple(lines))


def _human_dollars(value: float) -> str:
    """Compact money: 1.70T / 30.9B / 31.7M / 950K / 12 (magnitudes a human scans)."""
    for cut, suffix in ((1e12, "T"), (1e9, "B"), (1e6, "M"), (1e3, "K")):
        if abs(value) >= cut:
            scaled = value / cut
            return f"${scaled:.2f}{suffix}" if abs(scaled) < 10 else f"${scaled:.1f}{suffix}"
    return f"${value:,.0f}"


def _human_count(value: float) -> str:
    for cut, suffix in ((1e9, "B"), (1e6, "M"), (1e3, "K")):
        if abs(value) >= cut:
            return f"{value / cut:.1f}{suffix}"
    return f"{value:,.0f}"


def _section_securities(meta: MetadataResult, asof: date) -> Section:
    """Per-holding fund facts (cost, size, liquidity, age) with provenance.

    n/a is honest absence: an equity or physical-commodity trust legitimately
    lacks some fields — never substitute a guess for a missing published fact.
    """
    lines = [
        f"{'ticker':7}{'exp ratio':>10}{'AUM':>10}{'avg vol':>10}{'age':>7}   category — family",
        "-" * 78,
    ]
    for tk in sorted(meta.rows):
        m = meta.rows[tk]
        exp = f"{m.expense_ratio * 100:.2f}%" if m.expense_ratio is not None else _NA
        aum = _human_dollars(m.aum) if m.aum is not None else _NA
        vol = _human_count(m.avg_volume) if m.avg_volume is not None else _NA
        age = m.age_years(asof)
        age_s = f"{age:.1f}y" if age is not None else _NA
        desc = " — ".join(p for p in (m.category, m.family) if p) or _NA
        lines.append(f"{tk:7}{exp:>10}{aum:>10}{vol:>10}{age_s:>7}   {desc}")
    lines.append("-" * 78)
    n_cache = meta.n_cache
    lines.append(
        f"metadata: yfinance ({n_cache}/{len(meta.rows)} from cache, ≤7d old); "
        "values are published fund facts, not advice"
    )
    if meta.missing:
        lines.append(f"⚠ no metadata for: {', '.join(meta.missing)}")
    return Section("SECURITIES (know your holdings)", tuple(lines))


def _section_candidates(results: list[CandidateScreen]) -> Section:
    """The deterministic screen's verdicts — one block per candidate, every check
    named with its reason. Honest framing is structural: a pass is "sane, cheap,
    liquid, genuinely different", never a prediction."""
    lines: list[str] = []
    for r in results:
        lines.append(f"{r.ticker} — {r.verdict.upper()}  ({r.counts()})")
        for c in r.checks:
            lines.append(f"  [{c.status:>4}] {c.name}: {c.reason}")
        lines.append("")
    has_role = any(c.name == "role" for r in results for c in r.checks)
    lines.append(
        "screen = published facts + price history; PASS is necessary, not sufficient "
        + (
            "(the role row is a held-out simulation, not a prediction)"
            if has_role
            else "(no return prediction; add --target for the walk-forward role check)"
        )
    )
    return Section("CANDIDATES (deterministic screen)", tuple(lines))


def _section_backtest(bt: BacktestResult) -> Section:
    """Two-leg comparison (rebalanced vs buy-and-hold), drawdown-first."""
    legs = bt.legs
    lw, cw = 26, 24  # label width, per-leg column width

    def row(label: str, cells: list[str]) -> str:
        return f"{label:<{lw}}" + "".join(f"{c:>{cw}}" for c in cells)

    def ratio(x: float) -> str:
        return _NA if not math.isfinite(x) else f"{x:+.2f}"

    def dd_ci(ci: MetricCI) -> str:
        if not math.isfinite(ci.point):
            return _NA
        return f"{ci.low * 100:.1f}% .. {ci.high * 100:.1f}%"

    def ratio_ci(ci: MetricCI) -> str:
        if not math.isfinite(ci.point):
            return _NA
        return f"{ci.low:+.2f} .. {ci.high:+.2f}"

    lines = [
        row("", [leg.label for leg in legs]),
        "-" * (lw + cw * len(legs)),
        row("Max drawdown", [_pct_or_na(leg.risk.max_drawdown_ci.point) for leg in legs]),
        row("  95% CI", [dd_ci(leg.risk.max_drawdown_ci) for leg in legs]),
        row("Sharpe (252-basis)", [ratio(leg.risk.sharpe.point) for leg in legs]),
        row("  95% CI", [ratio_ci(leg.risk.sharpe) for leg in legs]),
        row("Sortino", [ratio(leg.risk.sortino.point) for leg in legs]),
        row("  95% CI", [ratio_ci(leg.risk.sortino) for leg in legs]),
        row("Annualized return", [_pct_or_na(leg.annualized_return) for leg in legs]),
        row("Final value", [f"${leg.final_value:,.0f}" for leg in legs]),
    ]
    if any(leg.risk.is_noisy for leg in legs):
        lines.append(
            f"  ⚠ short window (< {NOISY_THRESHOLD_DAYS} return-days ≈ 2y); treat as noisy."
        )
    if bt.missing:
        lines.append(f"  excluded (no price history): {', '.join(bt.missing)}")
    if bt.provenance:
        srcs = ", ".join(sorted({s for s, _ in bt.provenance.values()}))
        oldest = min((fa for _, fa in bt.provenance.values()), default=None)
        asof = f" · oldest fetch {oldest.date()}" if oldest is not None else ""
        lines.append(f"  prices: {srcs}{asof}")
    lines.append(
        "Rebalancing is discipline, not a prediction; past results don't guarantee future ones."
    )
    title = (
        f"BACKTEST (notional ${bt.initial:,.0f} · {bt.start} → {bt.end} · "
        "simulation, not a prediction)"
    )
    return Section(title, tuple(lines))


def _footer_section(
    prices: dict[str, PriceRow], missing_tickers: list[str], generated_at: datetime
) -> Section | None:
    lines: list[str] = []
    if missing_tickers:
        lines.append(f"Prices unavailable for: {', '.join(sorted(missing_tickers))}")
    if prices:
        lines.append(_provenance_footer(prices, generated_at))
    lines.append(_DISCLAIMER)
    return Section("", tuple(lines))


def _format_timedelta(td: timedelta) -> str:
    total = int(td.total_seconds())
    if total < 60:
        return f"{total}s"
    if total < 3600:
        return f"{total // 60}m"
    if total < 86400:
        return f"{total / 3600:.1f}h"
    return f"{total / 86400:.1f}d"


def _provenance_footer(prices: dict[str, PriceRow], generated_at: datetime) -> str:
    """One-line summary of where the prices came from + how fresh they are.

    Age is measured against `generated_at` (the run instant), not the wall clock,
    so the footer is deterministic given (prices, generated_at) and the age is the
    *real* staleness (now − the price's true fetched_at), not a fabricated 0s."""
    by_source: Counter[str] = Counter(p.source for p in prices.values())
    src_parts = ", ".join(f"{n} {s}" for s, n in sorted(by_source.items()))
    ages = [max(generated_at - p.fetched_at, timedelta(0)) for p in prices.values()]
    oldest = max(ages) if ages else timedelta(0)
    newest = min(ages) if ages else timedelta(0)
    if oldest == newest:
        fresh = _format_timedelta(newest)
    else:
        fresh = f"{_format_timedelta(newest)} .. {_format_timedelta(oldest)} old"
    asof_now = generated_at.strftime("%Y-%m-%d %H:%M UTC")
    return f"Prices: {src_parts}  (age: {fresh} as of {asof_now})"


# ── renderers: ReportData → str (one per output format) ─────────────────────


def render_text(data: ReportData) -> str:
    """Plain-text brief (the stdout / terminal form)."""
    blocks: list[str] = []
    for sec in data.sections:
        body = "\n".join(sec.lines)
        blocks.append(f"=== {sec.title} ===\n{body}" if sec.title else body)
    return "\n\n".join(blocks)


def render_markdown(data: ReportData) -> str:
    """Markdown brief (the ``reports/`` file form).

    Section bodies go in fenced code blocks so the monospace alignment of the
    holdings grid (and the leading-space sub-lines) survives in any viewer.
    The untitled footer renders as plain prose — one blank-line-separated
    paragraph per line, NOT wrapped in emphasis (provenance lines contain
    ``..`` and could contain ``_``, which would mangle italic spans).
    """
    blocks: list[str] = [f"# {data.title}"]
    for sec in data.sections:
        if sec.title:
            body = "\n".join(sec.lines)
            blocks.append(f"## {sec.title}\n\n```\n{body}\n```")
        else:
            blocks.append("\n\n".join(sec.lines))
    return "\n\n".join(blocks) + "\n"


def render_html(data: ReportData) -> str:
    """Self-contained HTML brief (the email-body form).

    Monospace ``<pre>`` blocks preserve the column alignment; everything is
    escaped. Inline styles only (email clients strip <style>/external CSS)."""
    pre = (
        "margin:0 0 16px;padding:12px;background:#f6f8fa;border-radius:6px;"
        "overflow-x:auto;font:13px/1.4 ui-monospace,Menlo,Consolas,monospace;"
        "white-space:pre"
    )
    parts: list[str] = [
        f'<h2 style="font-family:system-ui,sans-serif">{html.escape(data.title)}</h2>'
    ]
    for sec in data.sections:
        body = html.escape("\n".join(sec.lines))
        if sec.title:
            parts.append(
                f'<h3 style="font-family:system-ui,sans-serif;margin:20px 0 6px">'
                f"{html.escape(sec.title)}</h3>"
            )
            parts.append(f'<pre style="{pre}">{body}</pre>')
        else:
            footer = "<br>".join(html.escape(line) for line in sec.lines)
            parts.append(
                f'<p style="font:12px/1.5 system-ui,sans-serif;color:#666">{footer}</p>'
            )
    inner = "\n".join(parts)
    return (
        '<!doctype html><html><body style="max-width:760px;margin:0 auto;'
        f'padding:16px">{inner}</body></html>'
    )


def format_summary(
    state: DerivedState,
    prices: dict[str, PriceRow] | None = None,
    returns: ReturnsSummary | None = None,
    risk: RiskSummary | None = None,
    *,
    missing_tickers: list[str] | None = None,
) -> str:
    """Back-compat convenience: build the report and render it as plain text.

    ``true_twr`` is now read from ``returns.true_twr_annualized`` rather than
    passed separately (folded in at the composition root)."""
    return render_text(
        build_report_data(
            state, prices, returns, risk, missing_tickers=missing_tickers
        )
    )
